### ISSUE TITLE
Gemfileにgoogle-searchが２度入っている

### ISSUE THREAD

**Issue by kinchan33** [iine/iiname#30]
bundleすると、こうなる。

>Your Gemfile lists the gem google-search (>= 0) more than once.
>You should probably keep only one of them.
>While it's not a problem now, it could cause errors if you change the version of just one of them later.

**Comment by chrhsmt** [comment]
https://github.com/iine/iiname/commit/b14ec8844f9ddc94a615f392129bccdcaf7fb18a

直接マスターにコミットしてしまいましたが、直しました。

**Comment by kinchan33** [comment]
:+1:
