### ISSUE TITLE
テスト時の外部ネットワーク接続の仕方を調整する

### ISSUE THREAD

**Issue by kinchan33** [iine/iiname#33]
test時に外部ネットワークに繋がない橋本さん方針と
webapi接続のテストコードを書かないといけない、という相矛盾する項目を
橋本さんなどと調整して、webapiのテストコードの書けるようにする。

**Comment by chrhsmt** [comment]
google-search-helper.rbというようなファイルを作ってあって、ネットワークアクセスをスタブ化して使い回せるようにしてあるので、rakutenも同じように修正していきましょう。

**Comment by kinchan33** [comment]
これも対応がマスターにマージされたのでクローズします
