### ISSUE TITLE
controllerの中にwebapi検索のメソッドを書いてしまうの如何なものか？

### ISSUE THREAD

**Issue by kinchan33** [iine/iiname#34]
今はcontrollerの中に直接検索メソッドを書いているが、
独立したクラスにした方がいい気がする。
橋本さんと相談。

**Comment by chrhsmt** [comment]
iiname_engine.rbみたいなのを用意しているので、そこにうまくマージしていきましょう。

**Comment by kinchan33** [comment]
lib/iiname の下ですね。

**Comment by kinchan33** [comment]
4c092e9be05c9e38e56d45994410e1497c955f6b
にて統一

**Comment by kinchan33** [comment]
masterにマージできたのでクローズします
